/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .world25.glb 
*/

import React, { useRef, useState } from "react";
import { useGLTF, Html } from "@react-three/drei";

import Pin_1 from "./Pin_1";

export default function World25(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("world25.glb");

  const [hovered2, hover2] = useState(null);
  const [hovered3, hover3] = useState(null);
  const [hovered4, hover4] = useState(null);
  const [hovered5, hover5] = useState(null);
  const [hovered6, hover6] = useState(null);
  const [hovered7, hover7] = useState(null);

  const daeseongjeon = document.querySelector(".daeseongjeon");
  const gyoyuggwan = document.querySelector(".gyoyuggwan");
  const gyoyuggwan2 = document.querySelector(".gyoyuggwan2");
  const seongyosenteo = document.querySelector(".seongyosenteo");
  const visioncenter = document.querySelector(".visioncenter");
  const yeongsanbogjisenteo = document.querySelector(".yeongsanbogjisenteo");

  return (
    <group ref={group} {...props} dispose={null}>
      <directionalLight
        intensity={4.5}
        castShadow
        position={[0, 10, 4.5]}
        shadow-mapSize-width={512}
        shadow-mapSize-height={512}
        shadow-camera-far={30}
        shadow-camera-left={-30}
        shadow-camera-right={30}
        shadow-camera-top={30}
        shadow-camera-bottom={-30}
        color={"#fff2a9"}
      />
      <group name="Scene">
        <group name="daeseongjeon" scale={1}>
          <mesh
            name="Mesh036"
            geometry={nodes.Mesh036.geometry}
            material={materials["b-brick.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh036_1"
            geometry={nodes.Mesh036_1.geometry}
            material={materials["b-wall.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh036_2"
            geometry={nodes.Mesh036_2.geometry}
            material={materials["b-gray.002"]}
            receiveShadow
          />
          <mesh
            name="Mesh036_3"
            geometry={nodes.Mesh036_3.geometry}
            material={materials["b-gray.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh036_4"
            geometry={nodes.Mesh036_4.geometry}
            material={materials["b-stairs.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh036_5"
            geometry={nodes.Mesh036_5.geometry}
            material={materials["gravel_embedded_concrete.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh036_6"
            geometry={nodes.Mesh036_6.geometry}
            material={materials["b-lid.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh036_7"
            geometry={nodes.Mesh036_7.geometry}
            material={materials["b-handrail.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh036_8"
            geometry={nodes.Mesh036_8.geometry}
            material={materials["b-white2.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh036_9"
            geometry={nodes.Mesh036_9.geometry}
            material={materials["b-pot.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh036_10"
            geometry={nodes.Mesh036_10.geometry}
            material={materials["s-pot_grass.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh036_11"
            geometry={nodes.Mesh036_11.geometry}
            material={materials["b-slab.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh036_12"
            geometry={nodes.Mesh036_12.geometry}
            material={materials["Tiles 01.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh036_13"
            geometry={nodes.Mesh036_13.geometry}
            material={materials["b-rooftopslab-g"]}
            receiveShadow
          />
          <mesh
            name="Mesh036_14"
            geometry={nodes.Mesh036_14.geometry}
            material={materials["b-dark_g"]}
            receiveShadow
          />
          <mesh
            name="Mesh036_15"
            geometry={nodes.Mesh036_15.geometry}
            material={materials["b-glass"]}
            receiveShadow
          />
          <mesh
            name="Mesh036_16"
            geometry={nodes.Mesh036_16.geometry}
            material={materials["b-rooftopslab.001"]}
            receiveShadow
          />
        </group>
        <group name="gujomul" scale={1}>
          <mesh
            name="Mesh002"
            geometry={nodes.Mesh002.geometry}
            material={materials["Metal.006"]}
            receiveShadow
            castShadow
          />
          <mesh
            name="Mesh002_1"
            geometry={nodes.Mesh002_1.geometry}
            material={materials["s-white1"]}
            receiveShadow
            castShadow
          />
        </group>
        <group name="gyoyuggwan" scale={1}>
          <mesh
            name="Mesh021"
            geometry={nodes.Mesh021.geometry}
            material={materials["b-brown3.002"]}
            receiveShadow
          />
          <mesh
            name="Mesh021_1"
            geometry={nodes.Mesh021_1.geometry}
            material={materials["b-handrail.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh021_2"
            geometry={nodes.Mesh021_2.geometry}
            material={materials["b-stairs.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh021_3"
            geometry={nodes.Mesh021_3.geometry}
            material={materials["Tiles 01.002"]}
            receiveShadow
          />
          <mesh
            name="Mesh021_4"
            geometry={nodes.Mesh021_4.geometry}
            material={materials["b-blue.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh021_5"
            geometry={nodes.Mesh021_5.geometry}
            material={materials["b-yellow.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh021_6"
            geometry={nodes.Mesh021_6.geometry}
            material={materials["b-green.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh021_7"
            geometry={nodes.Mesh021_7.geometry}
            material={materials["b-slab.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh021_8"
            geometry={nodes.Mesh021_8.geometry}
            material={materials["b-rooftopslab.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh021_9"
            geometry={nodes.Mesh021_9.geometry}
            material={materials["b-glass"]}
            receiveShadow
          />
        </group>
        <group name="gyoyuggwan2" rotation={[0, 0, Math.PI]} scale={-1}>
          <mesh
            name="Mesh029"
            geometry={nodes.Mesh029.geometry}
            material={materials["b-brick.005"]}
            receiveShadow
          />
          <mesh
            name="Mesh029_1"
            geometry={nodes.Mesh029_1.geometry}
            material={materials["b-white2.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh029_2"
            geometry={nodes.Mesh029_2.geometry}
            material={materials["b-black"]}
            receiveShadow
          />
          <mesh
            name="Mesh029_3"
            geometry={nodes.Mesh029_3.geometry}
            material={materials["b-slab.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh029_4"
            geometry={nodes.Mesh029_4.geometry}
            material={materials["b-lid002"]}
            receiveShadow
          />
          <mesh
            name="Mesh029_5"
            geometry={nodes.Mesh029_5.geometry}
            material={materials["b-rooftopslab.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh029_6"
            geometry={nodes.Mesh029_6.geometry}
            material={materials["b-glass"]}
            receiveShadow
          />
        </group>
        <group name="seongyosenteo" scale={1}>
          <mesh
            name="Mesh016"
            geometry={nodes.Mesh016.geometry}
            material={materials["b-con_red.002"]}
            receiveShadow
          />
          <mesh
            name="Mesh016_1"
            geometry={nodes.Mesh016_1.geometry}
            material={materials["b-frame"]}
            receiveShadow
          />
          <mesh
            name="Mesh016_2"
            geometry={nodes.Mesh016_2.geometry}
            material={materials["b-slab.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh016_3"
            geometry={nodes.Mesh016_3.geometry}
            material={materials["b-door.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh016_4"
            geometry={nodes.Mesh016_4.geometry}
            material={materials["b-stairs.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh016_5"
            geometry={nodes.Mesh016_5.geometry}
            material={materials["b-rooftopslab.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh016_6"
            geometry={nodes.Mesh016_6.geometry}
            material={materials["b-glass"]}
            receiveShadow
          />
        </group>
        <group name="site" scale={1}>
          <mesh
            name="Mesh008"
            geometry={nodes.Mesh008.geometry}
            material={materials["s-stairs.003"]}
            receiveShadow
          />
          <mesh
            name="Mesh008_1"
            geometry={nodes.Mesh008_1.geometry}
            material={materials["s-pattern1.003"]}
            receiveShadow
          />
        </group>
        <group name="Vision_Center" scale={1}>
          <mesh
            name="Mesh023"
            geometry={nodes.Mesh023.geometry}
            material={materials["b-brick3.002"]}
            receiveShadow
          />
          <mesh
            name="Mesh023_1"
            geometry={nodes.Mesh023_1.geometry}
            material={materials["b-door.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh023_2"
            geometry={nodes.Mesh023_2.geometry}
            material={materials["b-slab.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh023_3"
            geometry={nodes.Mesh023_3.geometry}
            material={materials["b-rooftopslab.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh023_4"
            geometry={nodes.Mesh023_4.geometry}
            material={materials["b-glass"]}
            receiveShadow
          />
        </group>
        <group name="yeongsanbogjisenteo" scale={1}>
          <mesh
            name="Mesh010"
            geometry={nodes.Mesh010.geometry}
            material={materials["b-brick4.002"]}
            receiveShadow
          />
          <mesh
            name="Mesh010_1"
            geometry={nodes.Mesh010_1.geometry}
            material={materials["b-door.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh010_2"
            geometry={nodes.Mesh010_2.geometry}
            material={materials["b-slab.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh010_3"
            geometry={nodes.Mesh010_3.geometry}
            material={materials["b-rooftopslab.001"]}
            receiveShadow
          />
          <mesh
            name="Mesh010_4"
            geometry={nodes.Mesh010_4.geometry}
            material={materials["b-glass"]}
            receiveShadow
          />
        </group>
        <Pin_1 />
        <mesh
          geometry={nodes.cover_daeseongjeon.geometry}
          material={materials["Material #289"]}
          scale={1}
          onPointerOver={(e) => (
            e.stopPropagation(),
            hover7(true),
            daeseongjeon?.classList.add("active")
          )}
          onPointerOut={(e) => (
            e.stopPropagation(),
            hover7(false),
            daeseongjeon?.classList.remove("active")
          )}
          castShadow
          receiveShadow
        >
          <meshStandardMaterial
            color={hovered7 ? "gold" : "rgb(0, 0, 0)"}
            opacity={hovered7 ? "0.7" : "0"}
            transparent
          ></meshStandardMaterial>
          <Html position={[-3.8, 3.8, 0.8]}>
            <span
              className="daeseongjeon"
              onPointerOver={(e) => (e.stopPropagation(), hover7(true))}
              onPointerOut={(e) => hover7(false)}
              onClick={(e) => (
                e.stopPropagation(),
                window.parent.document
                  .querySelector(".left_box")
                  .setAttribute("class", "left_box"),
                window.parent.document
                  .querySelector(".left_box")
                  .classList.add("daeseongjeon")
              )}
            ></span>
          </Html>
        </mesh>
        <mesh
          geometry={nodes.cover_gyoyuggwan.geometry}
          material={materials["Material #289"]}
          scale={1}
          onPointerOver={(e) => (
            e.stopPropagation(),
            hover2(true),
            gyoyuggwan?.classList.add("active")
          )}
          onPointerOut={(e) => (
            e.stopPropagation(),
            hover2(false),
            gyoyuggwan?.classList.remove("active")
          )}
          castShadow
          receiveShadow
        >
          <meshStandardMaterial
            color={hovered2 ? "gold" : "rgb(0, 0, 0)"}
            opacity={hovered2 ? "0.7" : "0"}
            transparent
          ></meshStandardMaterial>
          <Html position={[-0.4, 5.6, 4]}>
            <span
              className="gyoyuggwan"
              onPointerOver={(e) => (e.stopPropagation(), hover2(true))}
              onPointerOut={(e) => hover2(false)}
              onClick={(e) => (
                e.stopPropagation(),
                window.parent.document
                  .querySelector(".left_box")
                  .setAttribute("class", "left_box"),
                window.parent.document
                  .querySelector(".left_box")
                  .classList.add("gyoyuggwan")
              )}
            ></span>
          </Html>
        </mesh>
        <mesh
          geometry={nodes.cover_seongyosenteo.geometry}
          material={materials["Material #289"]}
          scale={1}
          onPointerOver={(e) => (
            e.stopPropagation(),
            hover4(true),
            seongyosenteo?.classList.add("active")
          )}
          onPointerOut={(e) => (
            e.stopPropagation(),
            hover4(false),
            seongyosenteo?.classList.remove("active")
          )}
          castShadow
          receiveShadow
        >
          <meshStandardMaterial
            color={hovered4 ? "gold" : "rgb(0, 0, 0)"}
            opacity={hovered4 ? "0.7" : "0"}
            transparent
          ></meshStandardMaterial>
          <Html position={[4, 6.5, -2]}>
            <span
              className="seongyosenteo"
              onPointerOver={(e) => (e.stopPropagation(), hover4(true))}
              onPointerOut={(e) => hover4(false)}
              onClick={(e) => (
                e.stopPropagation(),
                window.parent.document
                  .querySelector(".left_box")
                  .setAttribute("class", "left_box"),
                window.parent.document
                  .querySelector(".left_box")
                  .classList.add("seongyosenteo")
              )}
            ></span>
          </Html>
        </mesh>
        <mesh
          geometry={nodes.cover_Vision_Center.geometry}
          material={materials["Material #289"]}
          scale={1}
          onPointerOver={(e) => (
            e.stopPropagation(),
            hover5(true),
            visioncenter?.classList.add("active")
          )}
          onPointerOut={(e) => (
            e.stopPropagation(),
            hover5(false),
            visioncenter?.classList.remove("active")
          )}
          castShadow
          receiveShadow
        >
          <meshStandardMaterial
            color={hovered5 ? "gold" : "rgb(0, 0, 0)"}
            opacity={hovered5 ? "0.7" : "0"}
            transparent
          ></meshStandardMaterial>
          <Html position={[5.5, 10, 0]}>
            <span
              className="visioncenter"
              onPointerOver={(e) => (e.stopPropagation(), hover5(true))}
              onPointerOut={(e) => hover5(false)}
              onClick={(e) => (
                e.stopPropagation(),
                window.parent.document
                  .querySelector(".left_box")
                  .setAttribute("class", "left_box"),
                window.parent.document
                  .querySelector(".left_box")
                  .classList.add("visioncenter")
              )}
            ></span>
          </Html>
        </mesh>
        <mesh
          geometry={nodes.cover_yeongsanbogjisenteo.geometry}
          material={materials["Material #289"]}
          scale={1}
          onPointerOver={(e) => (
            e.stopPropagation(),
            hover6(true),
            yeongsanbogjisenteo?.classList.add("active")
          )}
          onPointerOut={(e) => (
            e.stopPropagation(),
            hover6(false),
            yeongsanbogjisenteo?.classList.remove("active")
          )}
          castShadow
          receiveShadow
        >
          <meshStandardMaterial
            color={hovered6 ? "gold" : "rgb(0, 0, 0)"}
            opacity={hovered6 ? "0.7" : "0"}
            transparent
          ></meshStandardMaterial>
          <Html position={[5, 8.9, -4.5]}>
            <span
              className="yeongsanbogjisenteo"
              onPointerOver={(e) => (e.stopPropagation(), hover6(true))}
              onPointerOut={(e) => hover6(false)}
              onClick={(e) => (
                e.stopPropagation(),
                window.parent.document
                  .querySelector(".left_box")
                  .setAttribute("class", "left_box"),
                window.parent.document
                  .querySelector(".left_box")
                  .classList.add("yeongsanbogjisenteo")
              )}
            ></span>
          </Html>
        </mesh>
        <mesh
          geometry={nodes.cover_gyoyuggwan2.geometry}
          material={materials["Material #289.004"]}
          scale={1}
          onPointerOver={(e) => (
            e.stopPropagation(),
            hover3(true),
            gyoyuggwan2?.classList.add("active")
          )}
          onPointerOut={(e) => (
            e.stopPropagation(),
            hover3(false),
            gyoyuggwan2?.classList.remove("active")
          )}
          castShadow
          receiveShadow
        >
          <meshStandardMaterial
            color={hovered3 ? "gold" : "rgb(0, 0, 0)"}
            opacity={hovered3 ? "0.7" : "0"}
            transparent
          ></meshStandardMaterial>
          <Html position={[4, 8, 3.5]}>
            <span
              className="gyoyuggwan2"
              onPointerOver={(e) => (e.stopPropagation(), hover3(true))}
              onPointerOut={(e) => hover3(false)}
              onClick={(e) => (
                e.stopPropagation(),
                window.parent.document
                  .querySelector(".left_box")
                  .setAttribute("class", "left_box"),
                window.parent.document
                  .querySelector(".left_box")
                  .classList.add("gyoyuggwan2")
              )}
            ></span>
          </Html>
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("world25.glb");
